url: "https://docs.gekkegroninger.com"
# De url van de site

title: "Gekke Groninger"
description: "De docs van Gekke Groninger"
keep_files: [.git, README.md, .gitignore]
remote_theme: gekkegroninger/gekkegroninger.github.io

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-feed