title: "Gekke Groninger / Docs"
logo: /assets/img/logo.png
description: The docs page from Gekke Groninger
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
