url: "https://docs.gekkegroninger.com"
# De url van de site

title: "Gekke Groninger"
description: "De docs van Gekke Groninger"
keep_files: [.git, README.md, .gitignore]
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
google_analytics: "soon"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme